# Generated by Django 4.2.4 on 2023-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founddata',
            name='id_post',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID поста'),
        ),
    ]
