# Generated by Django 4.2.4 on 2023-08-15 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название соцсети')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(verbose_name='Статус таска')),
            ],
        ),
        migrations.CreateModel(
            name='VkParserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(verbose_name='Логин')),
                ('password', models.CharField(verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(verbose_name='Искомый текст')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('url_group', models.URLField(verbose_name='URL Группы')),
                ('numbers_of_posts', models.IntegerField(default=0, verbose_name='Количество постов')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.userprofile', verbose_name='Пользователь')),
                ('social_net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.socialnetwork', verbose_name='Социальная сеть')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.statustask', verbose_name='Статус таска')),
                ('vk_parser_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.vkparserdata', verbose_name='Данные для парсера')),
            ],
        ),
        migrations.CreateModel(
            name='FoundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField(verbose_name='ID поста')),
                ('date_post', models.DateTimeField(verbose_name='Дата публикации')),
                ('img', models.ImageField(null=True, upload_to='img/', verbose_name='Изображение')),
                ('found_text', models.TextField(verbose_name='Найденный текст')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.task', verbose_name='Таск')),
            ],
        ),
    ]
