# Generated by Django 4.2.4 on 2023-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founddata',
            name='link',
            field=models.CharField(default=1, verbose_name='Ссылка на публикацию'),
            preserve_default=False,
        ),
    ]
