# Generated by Django 4.2.4 on 2023-08-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='found_data',
            new_name='FoundData',
        ),
        migrations.RenameModel(
            old_name='search_data',
            new_name='SearchData',
        ),
        migrations.RenameField(
            model_name='founddata',
            old_name='url_groupe',
            new_name='url_group',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='url_groupe',
            new_name='url_group',
        ),
    ]
