# Generated by Django 4.2.4 on 2023-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_last_post',
            field=models.CharField(default=1, verbose_name='ID последнего поста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='founddata',
            name='date_post',
            field=models.CharField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='founddata',
            name='id_post',
            field=models.CharField(verbose_name='ID поста'),
        ),
        migrations.AlterField(
            model_name='founddata',
            name='img',
            field=models.TextField(null=True, verbose_name='Изображение'),
        ),
    ]
