# Generated by Django 4.2.4 on 2023-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_founddata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founddata',
            name='img',
            field=models.TextField(default=1, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
