# Generated by Django 4.2.4 on 2023-08-16 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_founddata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founddata',
            name='img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True, verbose_name='Фотография'), size=None),
        ),
    ]
