# Generated by Django 4.2.4 on 2023-08-16 12:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alter_founddata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founddata',
            name='img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name='Фотография'), blank=True, null=True, size=None),
        ),
    ]
